### PR TITLE
fix: do not try and authenticate when error reporting is disabled

### LINKED ISSUE #550: Only try to authenticate if reporting is enabled.
When running this package locally with `reportMode: 'never'` which [prevents any reporting](https://github.com/googleapis/nodejs-error-reporting/blob/419a5e176fb1c0ecfcf811457c6e5ea46a048506/src/google-apis/auth-client.ts#L176) but we still get an console message about not being able to find credential information because when creating the error reporting client [authentication is still attempted](https://github.com/googleapis/nodejs-error-reporting/blob/419a5e176fb1c0ecfcf811457c6e5ea46a048506/src/google-apis/auth-client.ts#L114).

Would it be possible for a similar check be put in before attempting this (both API key and obtaining an access token)?

### PR DESCRIPTION
**Pull request by comp615**
Fixes #550

### CODE REVIEW

**Review by losalex — APPROVED** [review]

**Comment by comp615** [comment]
@losalex anything additional needed from me to get the tests going and eventual merge/release? I think because I'm first time I might need someone to kick those off for me

File: src/google-apis/auth-client.ts [hunk 1]
```diff
@@ -110,7 +110,9 @@ export class RequestHandler extends Service {
     this._config = config;
     this._logger = logger;
 
-    if (tryAuthenticate) {
+    if (!this._config.getShouldReportErrorsToAPI()) {
```
Comment (losalex) [inline src/google-apis/auth-client.ts:113]: I believe you need to add an extra parameter controlling your feature (e.g. something like `authenticateIfErrorReportingIsOff` which by default should be `on`). The `getShouldReportErrorsToAPI` is existing feature and if for some reason this change contains a bug, there is no way to get `getShouldReportErrorsToAPI` working - e.g. we cannot tight the `getShouldReportErrorsToAPI` as the only flag controlling both features, hope it makes sense.

**Comment by losalex** [comment]
> @losalex anything additional needed from me to get the tests going and eventual merge/release? I think because I'm first time I might need someone to kick those off for me

Thanks @comp615 for making this change! Added a comment - basically you need to add additional config parameter controlling this feature and add all relevant tests to make sure that this flag by default does not impacts existing code and also does not introduces new failures. Also - did you run this change locally and tested E2E with GCP?

**Review by losalex — CHANGES_REQUESTED** [review]
Please see my comments

File: src/google-apis/auth-client.ts (hunk 1 above)
Comment (comp615) [reply src/google-apis/auth-client.ts:113]: I don't think of these as two separate features: _authentication exists only to report errors to the API_. If we are never reporting errors, why would we authenticate? It's not expected and that's why I believe `getShouldReportErrorsToAPI` should be used for both.

If there were a separate use-case aside from error reporting or other public functions in this client, then sure, they could be detached. But right now, if I were to make another config option, it unnecessarily complicates the configuration; it can only lead to cases where people get unexpected behavior by having the settings out of sync.

Comment (losalex) [reply src/google-apis/auth-client.ts:113]: To be honest, I am not very familiar with this code since I only recently was assigned to this repo. I agree with your comment and I think that adding redundant config is a bad practice. Thats said, this client library is used by many developers and any bugs related to this change might have an impact on existing users - thats a reason I asked for extra parameter. We can definitely make it right, so I would really appreciate if you can confirm if you ran this change E2E. In addition, would you be able to add system test for this functionality?

Comment (comp615) [reply src/google-apis/auth-client.ts:113]: Ok, yes I'll have this run in production for us for a few days and then also look into a system test. I had some trouble running those:
```
The project id (projectId) was not set in the env
The api key (apiKey) was not set as an env variable
The project number (projectNumber) was not set in the env
The key filename (keyFilename) was not set in the env
Skipping error-reporting system tests
``` 
Which is why I didn't write one initially, so I might be missing information on getting those to work but will look again.

Comment (comp615) [reply src/google-apis/auth-client.ts:113]: Ok, was able to get them going and wrote a new system-test assertion that fails with the old code and passes with the new.

Comment (losalex) [reply src/google-apis/auth-client.ts:113]: OK, thanks

**Review by losalex — APPROVED** [review]
LGTM - please run this change in GCP E2E with `getShouldReportErrorsToAPI` on/off to make sure it works as expected

**Comment by comp615** [comment]
> LGTM - please run this change in GCP E2E with `getShouldReportErrorsToAPI` on/off to make sure it works as expected

We've been running this E2E since last week and have not observed any new errors on either side of the boolean. That value is off/false in our test/development environments and on in our production environments.

**Review by losalex — COMMENTED** [review]
Seems there are bunch of system tests failing - see https://source.cloud.google.com/results/invocations/b2b15578-b54f-4360-8620-bbc5fece441b/targets/cloud-devrel%2Fclient-libraries%2Fnodejs%2Fpresubmit%2Fgoogleapis%2Fnodejs-error-reporting%2Fnode12%2Fsystem-test/log

**Comment by comp615** [comment]
Try that new build. I'm really struggling to get the error-reporting tests running locally, so kind of guessing at what the tests need. Would be much easier to debug in CI :-/
